#Evan Pollack 307278263

hostd:
	gcc -g -Wall -pedantic fd.c common.c -o hostd 


fcfs:
	gcc -g -Wall -pedantic fcfs.c common.c -o fcfs
fd:
	gcc -g -Wall -pedantic fd.c common.c -o fd 
rr:
	gcc -g -Wall -pedantic rr.c common.c -o rr
mm:
	gcc -g -Wall -pedantic mm.c common.c -o mm

clean:
	rm -rf hostd rr fcfs fd mm
